/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    copy: typeof import('./src/components/CountrySelector copy.vue')['default']
    CountrySelector: typeof import('./src/components/CountrySelector.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Month: typeof import('./src/components/calendar/Month.vue')['default']
    MonthControls: typeof import('./src/components/calendar/MonthControls.vue')['default']
    SearchButton: typeof import('./src/components/SearchButton.vue')['default']
    Select: typeof import('primevue/select')['default']
    YearSelector: typeof import('./src/components/YearSelector.vue')['default']
  }
}
