/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CountrySelector: typeof import('./src/components/CountrySelector.vue')['default']
    Day: typeof import('./src/components/calendar/Day.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    InfoDrawer: typeof import('./src/components/InfoDrawer.vue')['default']
    Month: typeof import('./src/components/calendar/Month.vue')['default']
    MonthControls: typeof import('./src/components/calendar/MonthControls.vue')['default']
    Select: typeof import('primevue/select')['default']
    YearSelector: typeof import('./src/components/YearSelector.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
